import { Navbar } from "@/components/Navbar";
import type { Metadata } from "next";
import "../app/globals.css"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-black text-white max-w-screen-2xl mx-auto px-4">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
